### ISSUE TITLE
Bad practice.

### ISSUE THREAD

**Issue by RoccoDev** [TheBloodHound/PlayerList#1]
Calling onCommand in your main class is bad practice and doesn't support aliases. Instead, create a class that implements CommandExecutor and register that executor in your onEnable.

TL;DR: checking if Command#getName() equals another string is bad practice, use CommandExecutors instead.

**Comment by TheBloodHound** [comment]
This repository is quite old so I've improved. I'll update the plugin and utilize CommandExecutors.
